name: $(versionNumber)

trigger:
- master

resources:
- repo: self

variables:
  version: '$(versionNumber)'
  clientAppFolder: 'client-app'
  apiFolder: 'api'

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'e9d0f44e-5ffb-4198-a9ae-99f36b5f6abb'
  imageRepository: 'wasoft'
  containerRegistry: 'wasoft.azurecr.io'
  dockerfilePath: '$(clientAppFolder)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: ClientApp
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: FileTransform@1
      displayName: 'Update package.json'
      inputs:
        folderPath: '$(clientAppFolder)'
        targetFiles: '**/package.json'
        fileType: json
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
