version: '3'
services:
  app-debug:
    build:
      context: ./client-app
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./client-app:/app
  app-tests:
    stdin_open: true
    build:
      context: ./client-app
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client-app:/app
    command: ['npm', 'run', 'test', '--', '--coverage']
